@base_url = http://localhost:7000/api/users/

### GET User All
GET {{base_url}} HTTP/1.1

### GET User One
GET {{base_url}}/1 HTTP/1.1

### POST User
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "John Fredy",
    "lastname": "Triana Camacho",
    "dni": "10101010101",
    "phone": "3132030102",
    "address": "Bogotá D.C."
}

### PUT User
PUT {{base_url}}/3 HTTP/1.1
Content-Type: application/json

{
    "name": "John Fredy 2",
    "lastname": "Triana Camacho 2",
    "dni": "10101010101 2",
    "phone": "3132030102 2",
    "address": "Bogotá D.C. 2"
}

### DELETE User
DELETE {{base_url}}/3 HTTP/1.1